@extends('frontend.layouts.app', ['title' => __('गृह')])
@section('content')
    <div class="container">
        <h1>Hello, world!
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse reprehenderit doloremque minima earum non et sunt quaerat tenetur inventore, mollitia harum expedita perspiciatis, quibusdam id magni dolore dignissimos, consectetur repellat.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde dicta dolores omnis quas, atque reiciendis eius vitae commodi ullam quia. Voluptatum hic labore et earum eum. Quae porro sed doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, recusandae? Ullam et corporis officia quae odio consectetur inventore, minima laudantium est voluptate harum quasi. Quae ex dignissimos officia natus odit!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo sapiente voluptates provident incidunt laborum numquam cumque dolor praesentium. Atque fugiat architecto hic sunt nostrum dolorem modi delectus deleniti! Veritatis, magnam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Est nesciunt soluta numquam assumenda quos. Voluptatem dolor similique obcaecati, magni cumque soluta asperiores nobis itaque nam ullam aliquam, dolorem totam quos!
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorem iusto vitae quaerat. Ducimus magni reiciendis nam, repellat dicta quibusdam fugit rem quia ipsam quam numquam, nesciunt minus dolorum! Itaque, placeat.
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse reprehenderit doloremque minima earum non et sunt quaerat tenetur inventore, mollitia harum expedita perspiciatis, quibusdam id magni dolore dignissimos, consectetur repellat.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde dicta dolores omnis quas, atque reiciendis eius vitae commodi ullam quia. Voluptatum hic labore et earum eum. Quae porro sed doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, recusandae? Ullam et corporis officia quae odio consectetur inventore, minima laudantium est voluptate harum quasi. Quae ex dignissimos officia natus odit!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo sapiente voluptates provident incidunt laborum numquam cumque dolor praesentium. Atque fugiat architecto hic sunt nostrum dolorem modi delectus deleniti! Veritatis, magnam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Est nesciunt soluta numquam assumenda quos. Voluptatem dolor similique obcaecati, magni cumque soluta asperiores nobis itaque nam ullam aliquam, dolorem totam quos!
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorem iusto vitae quaerat. Ducimus magni reiciendis nam, repellat dicta quibusdam fugit rem quia ipsam quam numquam, nesciunt minus dolorum! Itaque, placeat.
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse reprehenderit doloremque minima earum non et sunt quaerat tenetur inventore, mollitia harum expedita perspiciatis, quibusdam id magni dolore dignissimos, consectetur repellat.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde dicta dolores omnis quas, atque reiciendis eius vitae commodi ullam quia. Voluptatum hic labore et earum eum. Quae porro sed doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, recusandae? Ullam et corporis officia quae odio consectetur inventore, minima laudantium est voluptate harum quasi. Quae ex dignissimos officia natus odit!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo sapiente voluptates provident incidunt laborum numquam cumque dolor praesentium. Atque fugiat architecto hic sunt nostrum dolorem modi delectus deleniti! Veritatis, magnam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Est nesciunt soluta numquam assumenda quos. Voluptatem dolor similique obcaecati, magni cumque soluta asperiores nobis itaque nam ullam aliquam, dolorem totam quos!
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorem iusto vitae quaerat. Ducimus magni reiciendis nam, repellat dicta quibusdam fugit rem quia ipsam quam numquam, nesciunt minus dolorum! Itaque, placeat.
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse reprehenderit doloremque minima earum non et sunt quaerat tenetur inventore, mollitia harum expedita perspiciatis, quibusdam id magni dolore dignissimos, consectetur repellat.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde dicta dolores omnis quas, atque reiciendis eius vitae commodi ullam quia. Voluptatum hic labore et earum eum. Quae porro sed doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, recusandae? Ullam et corporis officia quae odio consectetur inventore, minima laudantium est voluptate harum quasi. Quae ex dignissimos officia natus odit!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo sapiente voluptates provident incidunt laborum numquam cumque dolor praesentium. Atque fugiat architecto hic sunt nostrum dolorem modi delectus deleniti! Veritatis, magnam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Est nesciunt soluta numquam assumenda quos. Voluptatem dolor similique obcaecati, magni cumque soluta asperiores nobis itaque nam ullam aliquam, dolorem totam quos!
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorem iusto vitae quaerat. Ducimus magni reiciendis nam, repellat dicta quibusdam fugit rem quia ipsam quam numquam, nesciunt minus dolorum! Itaque, placeat.
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse reprehenderit doloremque minima earum non et sunt quaerat tenetur inventore, mollitia harum expedita perspiciatis, quibusdam id magni dolore dignissimos, consectetur repellat.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde dicta dolores omnis quas, atque reiciendis eius vitae commodi ullam quia. Voluptatum hic labore et earum eum. Quae porro sed doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, recusandae? Ullam et corporis officia quae odio consectetur inventore, minima laudantium est voluptate harum quasi. Quae ex dignissimos officia natus odit!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo sapiente voluptates provident incidunt laborum numquam cumque dolor praesentium. Atque fugiat architecto hic sunt nostrum dolorem modi delectus deleniti! Veritatis, magnam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Est nesciunt soluta numquam assumenda quos. Voluptatem dolor similique obcaecati, magni cumque soluta asperiores nobis itaque nam ullam aliquam, dolorem totam quos!
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorem iusto vitae quaerat. Ducimus magni reiciendis nam, repellat dicta quibusdam fugit rem quia ipsam quam numquam, nesciunt minus dolorum! Itaque, placeat.
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse reprehenderit doloremque minima earum non et sunt quaerat tenetur inventore, mollitia harum expedita perspiciatis, quibusdam id magni dolore dignissimos, consectetur repellat.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde dicta dolores omnis quas, atque reiciendis eius vitae commodi ullam quia. Voluptatum hic labore et earum eum. Quae porro sed doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, recusandae? Ullam et corporis officia quae odio consectetur inventore, minima laudantium est voluptate harum quasi. Quae ex dignissimos officia natus odit!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo sapiente voluptates provident incidunt laborum numquam cumque dolor praesentium. Atque fugiat architecto hic sunt nostrum dolorem modi delectus deleniti! Veritatis, magnam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Est nesciunt soluta numquam assumenda quos. Voluptatem dolor similique obcaecati, magni cumque soluta asperiores nobis itaque nam ullam aliquam, dolorem totam quos!
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorem iusto vitae quaerat. Ducimus magni reiciendis nam, repellat dicta quibusdam fugit rem quia ipsam quam numquam, nesciunt minus dolorum! Itaque, placeat.
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse reprehenderit doloremque minima earum non et sunt quaerat tenetur inventore, mollitia harum expedita perspiciatis, quibusdam id magni dolore dignissimos, consectetur repellat.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde dicta dolores omnis quas, atque reiciendis eius vitae commodi ullam quia. Voluptatum hic labore et earum eum. Quae porro sed doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, recusandae? Ullam et corporis officia quae odio consectetur inventore, minima laudantium est voluptate harum quasi. Quae ex dignissimos officia natus odit!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo sapiente voluptates provident incidunt laborum numquam cumque dolor praesentium. Atque fugiat architecto hic sunt nostrum dolorem modi delectus deleniti! Veritatis, magnam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Est nesciunt soluta numquam assumenda quos. Voluptatem dolor similique obcaecati, magni cumque soluta asperiores nobis itaque nam ullam aliquam, dolorem totam quos!
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorem iusto vitae quaerat. Ducimus magni reiciendis nam, repellat dicta quibusdam fugit rem quia ipsam quam numquam, nesciunt minus dolorum! Itaque, placeat.
            Lorem ipsum dolor sit amet consectetur, adipisicing elit. Esse reprehenderit doloremque minima earum non et sunt quaerat tenetur inventore, mollitia harum expedita perspiciatis, quibusdam id magni dolore dignissimos, consectetur repellat.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Unde dicta dolores omnis quas, atque reiciendis eius vitae commodi ullam quia. Voluptatum hic labore et earum eum. Quae porro sed doloremque.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Perspiciatis, recusandae? Ullam et corporis officia quae odio consectetur inventore, minima laudantium est voluptate harum quasi. Quae ex dignissimos officia natus odit!
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Nemo sapiente voluptates provident incidunt laborum numquam cumque dolor praesentium. Atque fugiat architecto hic sunt nostrum dolorem modi delectus deleniti! Veritatis, magnam.
            Lorem ipsum dolor sit amet consectetur adipisicing elit. Est nesciunt soluta numquam assumenda quos. Voluptatem dolor similique obcaecati, magni cumque soluta asperiores nobis itaque nam ullam aliquam, dolorem totam quos!
            Lorem ipsum, dolor sit amet consectetur adipisicing elit. Dolorem iusto vitae quaerat. Ducimus magni reiciendis nam, repellat dicta quibusdam fugit rem quia ipsam quam numquam, nesciunt minus dolorum! Itaque, placeat.

        </h1>
    </div>
@endsection
